// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.AlgorithmDataOnDemand;
import io.algorithms.entity.AlgorithmEntity;
import io.algorithms.entity.AlgorithmIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AlgorithmIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AlgorithmIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AlgorithmIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AlgorithmIntegrationTest: @Transactional;
    
    @Autowired
    private AlgorithmDataOnDemand AlgorithmIntegrationTest.dod;
    
    @Test
    public void AlgorithmIntegrationTest.testCountAlgorithmEntitys() {
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to initialize correctly", dod.getRandomAlgorithmEntity());
        long count = AlgorithmEntity.countAlgorithmEntitys();
        Assert.assertTrue("Counter for 'AlgorithmEntity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AlgorithmIntegrationTest.testFindAlgorithmEntity() {
        AlgorithmEntity obj = dod.getRandomAlgorithmEntity();
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to provide an identifier", id);
        obj = AlgorithmEntity.findAlgorithmEntity(id);
        Assert.assertNotNull("Find method for 'AlgorithmEntity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AlgorithmEntity' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AlgorithmIntegrationTest.testFindAllAlgorithmEntitys() {
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to initialize correctly", dod.getRandomAlgorithmEntity());
        long count = AlgorithmEntity.countAlgorithmEntitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'AlgorithmEntity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AlgorithmEntity> result = AlgorithmEntity.findAllAlgorithmEntitys();
        Assert.assertNotNull("Find all method for 'AlgorithmEntity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AlgorithmEntity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AlgorithmIntegrationTest.testFindAlgorithmEntityEntries() {
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to initialize correctly", dod.getRandomAlgorithmEntity());
        long count = AlgorithmEntity.countAlgorithmEntitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AlgorithmEntity> result = AlgorithmEntity.findAlgorithmEntityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AlgorithmEntity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AlgorithmEntity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AlgorithmIntegrationTest.testFlush() {
        AlgorithmEntity obj = dod.getRandomAlgorithmEntity();
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to provide an identifier", id);
        obj = AlgorithmEntity.findAlgorithmEntity(id);
        Assert.assertNotNull("Find method for 'AlgorithmEntity' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAlgorithmEntity(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AlgorithmEntity' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AlgorithmIntegrationTest.testMergeUpdate() {
        AlgorithmEntity obj = dod.getRandomAlgorithmEntity();
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to provide an identifier", id);
        obj = AlgorithmEntity.findAlgorithmEntity(id);
        boolean modified =  dod.modifyAlgorithmEntity(obj);
        Integer currentVersion = obj.getVersion();
        AlgorithmEntity merged = (AlgorithmEntity)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AlgorithmEntity' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AlgorithmIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to initialize correctly", dod.getRandomAlgorithmEntity());
        AlgorithmEntity obj = dod.getNewTransientAlgorithmEntity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AlgorithmEntity' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AlgorithmEntity' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AlgorithmIntegrationTest.testRemove() {
        AlgorithmEntity obj = dod.getRandomAlgorithmEntity();
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AlgorithmEntity' failed to provide an identifier", id);
        obj = AlgorithmEntity.findAlgorithmEntity(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AlgorithmEntity' with identifier '" + id + "'", AlgorithmEntity.findAlgorithmEntity(id));
    }
    
}
