// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.DataFormat;
import io.algorithms.entity.DataSetEntity;
import io.algorithms.entity.DataSetDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DataSetDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DataSetDataOnDemand: @Component;
    
    private Random DataSetDataOnDemand.rnd = new SecureRandom();
    
    private List<DataSetEntity> DataSetDataOnDemand.data;
    
    public DataSetEntity DataSetDataOnDemand.getNewTransientDataSet(int index) {
        DataSetEntity obj = new DataSetEntity();
        setCreateTime(obj, index);
        setDescription(obj, index);
        setFormat(obj, index);
        setLastModifiedTime(obj, index);
        setLastModifiedUserUri(obj, index);
        setName(obj, index);
        setOwnerGroupUri(obj, index);
        setOwnerUri(obj, index);
        setParentGroupUri(obj, index);
        setSize(obj, index);
        setUri(obj, index);
        return obj;
    }
    
    public void DataSetDataOnDemand.setCreateTime(DataSetEntity obj, int index) {
        Date createTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateTime(createTime);
    }
    
    public void DataSetDataOnDemand.setDescription(DataSetEntity obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void DataSetDataOnDemand.setFormat(DataSetEntity obj, int index) {
        DataFormat format = DataFormat.class.getEnumConstants()[0];
        obj.setFormat(format);
    }
    
    public void DataSetDataOnDemand.setLastModifiedTime(DataSetEntity obj, int index) {
        Date lastModifiedTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLastModifiedTime(lastModifiedTime);
    }
    
    public void DataSetDataOnDemand.setLastModifiedUserUri(DataSetEntity obj, int index) {
        String lastModifiedUserUri = "lastModifiedUserUri_" + index;
        obj.setLastModifiedUserUri(lastModifiedUserUri);
    }
    
    public void DataSetDataOnDemand.setName(DataSetEntity obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void DataSetDataOnDemand.setOwnerGroupUri(DataSetEntity obj, int index) {
        String ownerGroupUri = "ownerGroupUri_" + index;
        obj.setOwnerGroupUri(ownerGroupUri);
    }
    
    public void DataSetDataOnDemand.setOwnerUri(DataSetEntity obj, int index) {
        String ownerUri = "ownerUri_" + index;
        obj.setOwnerUri(ownerUri);
    }
    
    public void DataSetDataOnDemand.setParentGroupUri(DataSetEntity obj, int index) {
        String parentGroupUri = "parentGroupUri_" + index;
        obj.setParentGroupUri(parentGroupUri);
    }
    
    public void DataSetDataOnDemand.setSize(DataSetEntity obj, int index) {
        Long size = new Integer(index).longValue();
        obj.setSize(size);
    }
    
    public void DataSetDataOnDemand.setUri(DataSetEntity obj, int index) {
        String uri = "uri_" + index;
        obj.setUri(uri);
    }
    
    public DataSetEntity DataSetDataOnDemand.getSpecificDataSet(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DataSetEntity obj = data.get(index);
        Long id = obj.getId();
        return DataSetEntity.findDataSetEntity(id);
    }
    
    public DataSetEntity DataSetDataOnDemand.getRandomDataSet() {
        init();
        DataSetEntity obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DataSetEntity.findDataSetEntity(id);
    }
    
    public boolean DataSetDataOnDemand.modifyDataSet(DataSetEntity obj) {
        return false;
    }
    
    public void DataSetDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DataSetEntity.findDataSetEntityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DataSet' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DataSetEntity>();
        for (int i = 0; i < 10; i++) {
            DataSetEntity obj = getNewTransientDataSet(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
