// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.DataSetDataOnDemand;
import io.algorithms.entity.DataSetEntityBase;
import io.algorithms.entity.DataSetIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DataSetIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DataSetIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DataSetIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DataSetIntegrationTest: @Transactional;
    
    @Autowired
    private DataSetDataOnDemand DataSetIntegrationTest.dod;
    
    @Test
    public void DataSetIntegrationTest.testCountDataSetEntityBases() {
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to initialize correctly", dod.getRandomDataSetEntityBase());
        long count = DataSetEntityBase.countDataSetEntityBases();
        Assert.assertTrue("Counter for 'DataSetEntityBase' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DataSetIntegrationTest.testFindDataSetEntityBase() {
        DataSetEntityBase obj = dod.getRandomDataSetEntityBase();
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to provide an identifier", id);
        obj = DataSetEntityBase.findDataSetEntityBase(id);
        Assert.assertNotNull("Find method for 'DataSetEntityBase' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DataSetEntityBase' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DataSetIntegrationTest.testFindAllDataSetEntityBases() {
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to initialize correctly", dod.getRandomDataSetEntityBase());
        long count = DataSetEntityBase.countDataSetEntityBases();
        Assert.assertTrue("Too expensive to perform a find all test for 'DataSetEntityBase', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DataSetEntityBase> result = DataSetEntityBase.findAllDataSetEntityBases();
        Assert.assertNotNull("Find all method for 'DataSetEntityBase' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DataSetEntityBase' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DataSetIntegrationTest.testFindDataSetEntityBaseEntries() {
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to initialize correctly", dod.getRandomDataSetEntityBase());
        long count = DataSetEntityBase.countDataSetEntityBases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DataSetEntityBase> result = DataSetEntityBase.findDataSetEntityBaseEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DataSetEntityBase' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DataSetEntityBase' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DataSetIntegrationTest.testFlush() {
        DataSetEntityBase obj = dod.getRandomDataSetEntityBase();
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to provide an identifier", id);
        obj = DataSetEntityBase.findDataSetEntityBase(id);
        Assert.assertNotNull("Find method for 'DataSetEntityBase' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDataSetEntityBase(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DataSetEntityBase' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataSetIntegrationTest.testMergeUpdate() {
        DataSetEntityBase obj = dod.getRandomDataSetEntityBase();
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to provide an identifier", id);
        obj = DataSetEntityBase.findDataSetEntityBase(id);
        boolean modified =  dod.modifyDataSetEntityBase(obj);
        Integer currentVersion = obj.getVersion();
        DataSetEntityBase merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DataSetEntityBase' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DataSetIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to initialize correctly", dod.getRandomDataSetEntityBase());
        DataSetEntityBase obj = dod.getNewTransientDataSetEntityBase(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DataSetEntityBase' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'DataSetEntityBase' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DataSetIntegrationTest.testRemove() {
        DataSetEntityBase obj = dod.getRandomDataSetEntityBase();
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DataSetEntityBase' failed to provide an identifier", id);
        obj = DataSetEntityBase.findDataSetEntityBase(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DataSetEntityBase' with identifier '" + id + "'", DataSetEntityBase.findDataSetEntityBase(id));
    }
    
}
