// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.FieldDataOnDemand;
import io.algorithms.entity.FieldEntity;
import io.algorithms.entity.FieldIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FieldIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FieldIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FieldIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FieldIntegrationTest: @Transactional;
    
    @Autowired
    private FieldDataOnDemand FieldIntegrationTest.dod;
    
    @Test
    public void FieldIntegrationTest.testCountFieldEntitys() {
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to initialize correctly", dod.getRandomFieldEntity());
        long count = FieldEntity.countFieldEntitys();
        Assert.assertTrue("Counter for 'FieldEntity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FieldIntegrationTest.testFindFieldEntity() {
        FieldEntity obj = dod.getRandomFieldEntity();
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to provide an identifier", id);
        obj = FieldEntity.findFieldEntity(id);
        Assert.assertNotNull("Find method for 'FieldEntity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FieldEntity' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FieldIntegrationTest.testFindAllFieldEntitys() {
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to initialize correctly", dod.getRandomFieldEntity());
        long count = FieldEntity.countFieldEntitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'FieldEntity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FieldEntity> result = FieldEntity.findAllFieldEntitys();
        Assert.assertNotNull("Find all method for 'FieldEntity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FieldEntity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FieldIntegrationTest.testFindFieldEntityEntries() {
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to initialize correctly", dod.getRandomFieldEntity());
        long count = FieldEntity.countFieldEntitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FieldEntity> result = FieldEntity.findFieldEntityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FieldEntity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FieldEntity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FieldIntegrationTest.testFlush() {
        FieldEntity obj = dod.getRandomFieldEntity();
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to provide an identifier", id);
        obj = FieldEntity.findFieldEntity(id);
        Assert.assertNotNull("Find method for 'FieldEntity' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFieldEntity(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FieldEntity' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldIntegrationTest.testMergeUpdate() {
        FieldEntity obj = dod.getRandomFieldEntity();
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to provide an identifier", id);
        obj = FieldEntity.findFieldEntity(id);
        boolean modified =  dod.modifyFieldEntity(obj);
        Integer currentVersion = obj.getVersion();
        FieldEntity merged = (FieldEntity)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FieldEntity' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to initialize correctly", dod.getRandomFieldEntity());
        FieldEntity obj = dod.getNewTransientFieldEntity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FieldEntity' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'FieldEntity' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FieldIntegrationTest.testRemove() {
        FieldEntity obj = dod.getRandomFieldEntity();
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FieldEntity' failed to provide an identifier", id);
        obj = FieldEntity.findFieldEntity(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FieldEntity' with identifier '" + id + "'", FieldEntity.findFieldEntity(id));
    }
    
}
