// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.GroupDataOnDemand;
import io.algorithms.entity.GroupEntityBase;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect GroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GroupDataOnDemand: @Component;
    
    private Random GroupDataOnDemand.rnd = new SecureRandom();
    
    private List<GroupEntityBase> GroupDataOnDemand.data;
    
    public GroupEntityBase GroupDataOnDemand.getNewTransientGroupEntityBase(int index) {
        GroupEntityBase obj = new GroupEntityBase();
        setCreateTime(obj, index);
        setDescription(obj, index);
        setLastModifiedTime(obj, index);
        setLastModifiedUserUri(obj, index);
        setName(obj, index);
        setOwnerGroupUri(obj, index);
        setOwnerUri(obj, index);
        setParentGroupUri(obj, index);
        setUri(obj, index);
        return obj;
    }
    
    public void GroupDataOnDemand.setCreateTime(GroupEntityBase obj, int index) {
        Date createTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateTime(createTime);
    }
    
    public void GroupDataOnDemand.setDescription(GroupEntityBase obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void GroupDataOnDemand.setLastModifiedTime(GroupEntityBase obj, int index) {
        Date lastModifiedTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLastModifiedTime(lastModifiedTime);
    }
    
    public void GroupDataOnDemand.setLastModifiedUserUri(GroupEntityBase obj, int index) {
        String lastModifiedUserUri = "lastModifiedUserUri_" + index;
        obj.setLastModifiedUserUri(lastModifiedUserUri);
    }
    
    public void GroupDataOnDemand.setName(GroupEntityBase obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void GroupDataOnDemand.setOwnerGroupUri(GroupEntityBase obj, int index) {
        String ownerGroupUri = "ownerGroupUri_" + index;
        obj.setOwnerGroupUri(ownerGroupUri);
    }
    
    public void GroupDataOnDemand.setOwnerUri(GroupEntityBase obj, int index) {
        String ownerUri = "ownerUri_" + index;
        obj.setOwnerUri(ownerUri);
    }
    
    public void GroupDataOnDemand.setParentGroupUri(GroupEntityBase obj, int index) {
        String parentGroupUri = "parentGroupUri_" + index;
        obj.setParentGroupUri(parentGroupUri);
    }
    
    public void GroupDataOnDemand.setUri(GroupEntityBase obj, int index) {
        String uri = "uri_" + index;
        obj.setUri(uri);
    }
    
    public GroupEntityBase GroupDataOnDemand.getSpecificGroupEntityBase(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        GroupEntityBase obj = data.get(index);
        Long id = obj.getId();
        return GroupEntityBase.findGroupEntityBase(id);
    }
    
    public GroupEntityBase GroupDataOnDemand.getRandomGroupEntityBase() {
        init();
        GroupEntityBase obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return GroupEntityBase.findGroupEntityBase(id);
    }
    
    public boolean GroupDataOnDemand.modifyGroupEntityBase(GroupEntityBase obj) {
        return false;
    }
    
    public void GroupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = GroupEntityBase.findGroupEntityBaseEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'GroupEntityBase' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<GroupEntityBase>();
        for (int i = 0; i < 10; i++) {
            GroupEntityBase obj = getNewTransientGroupEntityBase(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
