// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.JobDataOnDemand;
import io.algorithms.entity.JobEntity;
import io.algorithms.entity.JobStatus;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect JobDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JobDataOnDemand: @Component;
    
    private Random JobDataOnDemand.rnd = new SecureRandom();
    
    private List<JobEntity> JobDataOnDemand.data;
    
    public JobEntity JobDataOnDemand.getNewTransientJobEntity(int index) {
        JobEntity obj = new JobEntity();
        setCreateTime(obj, index);
        setDescription(obj, index);
        setLastModifiedTime(obj, index);
        setLastModifiedUserUri(obj, index);
        setName(obj, index);
        setOwnerGroupUri(obj, index);
        setOwnerUri(obj, index);
        setParentGroupUri(obj, index);
        setStatus(obj, index);
        setUri(obj, index);
        return obj;
    }
    
    public void JobDataOnDemand.setCreateTime(JobEntity obj, int index) {
        Date createTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateTime(createTime);
    }
    
    public void JobDataOnDemand.setDescription(JobEntity obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void JobDataOnDemand.setLastModifiedTime(JobEntity obj, int index) {
        Date lastModifiedTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLastModifiedTime(lastModifiedTime);
    }
    
    public void JobDataOnDemand.setLastModifiedUserUri(JobEntity obj, int index) {
        String lastModifiedUserUri = "lastModifiedUserUri_" + index;
        obj.setLastModifiedUserUri(lastModifiedUserUri);
    }
    
    public void JobDataOnDemand.setName(JobEntity obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void JobDataOnDemand.setOwnerGroupUri(JobEntity obj, int index) {
        String ownerGroupUri = "ownerGroupUri_" + index;
        obj.setOwnerGroupUri(ownerGroupUri);
    }
    
    public void JobDataOnDemand.setOwnerUri(JobEntity obj, int index) {
        String ownerUri = "ownerUri_" + index;
        obj.setOwnerUri(ownerUri);
    }
    
    public void JobDataOnDemand.setParentGroupUri(JobEntity obj, int index) {
        String parentGroupUri = "parentGroupUri_" + index;
        obj.setParentGroupUri(parentGroupUri);
    }
    
    public void JobDataOnDemand.setStatus(JobEntity obj, int index) {
        JobStatus status = JobStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void JobDataOnDemand.setUri(JobEntity obj, int index) {
        String uri = "uri_" + index;
        obj.setUri(uri);
    }
    
    public JobEntity JobDataOnDemand.getSpecificJobEntity(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JobEntity obj = data.get(index);
        Long id = obj.getId();
        return JobEntity.findJobEntity(id);
    }
    
    public JobEntity JobDataOnDemand.getRandomJobEntity() {
        init();
        JobEntity obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JobEntity.findJobEntity(id);
    }
    
    public boolean JobDataOnDemand.modifyJobEntity(JobEntity obj) {
        return false;
    }
    
    public void JobDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JobEntity.findJobEntityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JobEntity' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JobEntity>();
        for (int i = 0; i < 10; i++) {
            JobEntity obj = getNewTransientJobEntity(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
