// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.JobDataOnDemand;
import io.algorithms.entity.JobEntity;
import io.algorithms.entity.JobIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JobIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JobIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JobIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JobIntegrationTest: @Transactional;
    
    @Autowired
    private JobDataOnDemand JobIntegrationTest.dod;
    
    @Test
    public void JobIntegrationTest.testCountJobEntitys() {
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to initialize correctly", dod.getRandomJobEntity());
        long count = JobEntity.countJobEntitys();
        Assert.assertTrue("Counter for 'JobEntity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JobIntegrationTest.testFindJobEntity() {
        JobEntity obj = dod.getRandomJobEntity();
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to provide an identifier", id);
        obj = JobEntity.findJobEntity(id);
        Assert.assertNotNull("Find method for 'JobEntity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JobEntity' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JobIntegrationTest.testFindAllJobEntitys() {
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to initialize correctly", dod.getRandomJobEntity());
        long count = JobEntity.countJobEntitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'JobEntity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JobEntity> result = JobEntity.findAllJobEntitys();
        Assert.assertNotNull("Find all method for 'JobEntity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JobEntity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JobIntegrationTest.testFindJobEntityEntries() {
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to initialize correctly", dod.getRandomJobEntity());
        long count = JobEntity.countJobEntitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JobEntity> result = JobEntity.findJobEntityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JobEntity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JobEntity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JobIntegrationTest.testFlush() {
        JobEntity obj = dod.getRandomJobEntity();
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to provide an identifier", id);
        obj = JobEntity.findJobEntity(id);
        Assert.assertNotNull("Find method for 'JobEntity' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJobEntity(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JobEntity' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobIntegrationTest.testMergeUpdate() {
        JobEntity obj = dod.getRandomJobEntity();
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to provide an identifier", id);
        obj = JobEntity.findJobEntity(id);
        boolean modified =  dod.modifyJobEntity(obj);
        Integer currentVersion = obj.getVersion();
        JobEntity merged = (JobEntity)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JobEntity' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to initialize correctly", dod.getRandomJobEntity());
        JobEntity obj = dod.getNewTransientJobEntity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JobEntity' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'JobEntity' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JobIntegrationTest.testRemove() {
        JobEntity obj = dod.getRandomJobEntity();
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobEntity' failed to provide an identifier", id);
        obj = JobEntity.findJobEntity(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JobEntity' with identifier '" + id + "'", JobEntity.findJobEntity(id));
    }
    
}
