// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.UserDataOnDemand;
import io.algorithms.entity.UserEntityBase;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserDataOnDemand: @Component;
    
    private Random UserDataOnDemand.rnd = new SecureRandom();
    
    private List<UserEntityBase> UserDataOnDemand.data;
    
    public UserEntityBase UserDataOnDemand.getNewTransientUserEntityBase(int index) {
        UserEntityBase obj = new UserEntityBase();
        setCreateTime(obj, index);
        setLastModifiedTime(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void UserDataOnDemand.setCreateTime(UserEntityBase obj, int index) {
        Date createTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateTime(createTime);
    }
    
    public void UserDataOnDemand.setLastModifiedTime(UserEntityBase obj, int index) {
        Date lastModifiedTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLastModifiedTime(lastModifiedTime);
    }
    
    public void UserDataOnDemand.setName(UserEntityBase obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public UserEntityBase UserDataOnDemand.getSpecificUserEntityBase(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserEntityBase obj = data.get(index);
        Long id = obj.getId();
        return UserEntityBase.findUserEntityBase(id);
    }
    
    public UserEntityBase UserDataOnDemand.getRandomUserEntityBase() {
        init();
        UserEntityBase obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UserEntityBase.findUserEntityBase(id);
    }
    
    public boolean UserDataOnDemand.modifyUserEntityBase(UserEntityBase obj) {
        return false;
    }
    
    public void UserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserEntityBase.findUserEntityBaseEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserEntityBase' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserEntityBase>();
        for (int i = 0; i < 10; i++) {
            UserEntityBase obj = getNewTransientUserEntityBase(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
