// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.UserDataOnDemand;
import io.algorithms.entity.UserEntityBase;
import io.algorithms.entity.UserIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserIntegrationTest: @Transactional;
    
    @Autowired
    private UserDataOnDemand UserIntegrationTest.dod;
    
    @Test
    public void UserIntegrationTest.testCountUserEntityBases() {
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to initialize correctly", dod.getRandomUserEntityBase());
        long count = UserEntityBase.countUserEntityBases();
        Assert.assertTrue("Counter for 'UserEntityBase' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserIntegrationTest.testFindUserEntityBase() {
        UserEntityBase obj = dod.getRandomUserEntityBase();
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to provide an identifier", id);
        obj = UserEntityBase.findUserEntityBase(id);
        Assert.assertNotNull("Find method for 'UserEntityBase' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserEntityBase' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserIntegrationTest.testFindAllUserEntityBases() {
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to initialize correctly", dod.getRandomUserEntityBase());
        long count = UserEntityBase.countUserEntityBases();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserEntityBase', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserEntityBase> result = UserEntityBase.findAllUserEntityBases();
        Assert.assertNotNull("Find all method for 'UserEntityBase' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserEntityBase' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserIntegrationTest.testFindUserEntityBaseEntries() {
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to initialize correctly", dod.getRandomUserEntityBase());
        long count = UserEntityBase.countUserEntityBases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserEntityBase> result = UserEntityBase.findUserEntityBaseEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserEntityBase' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserEntityBase' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserIntegrationTest.testFlush() {
        UserEntityBase obj = dod.getRandomUserEntityBase();
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to provide an identifier", id);
        obj = UserEntityBase.findUserEntityBase(id);
        Assert.assertNotNull("Find method for 'UserEntityBase' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserEntityBase(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserEntityBase' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserIntegrationTest.testMergeUpdate() {
        UserEntityBase obj = dod.getRandomUserEntityBase();
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to provide an identifier", id);
        obj = UserEntityBase.findUserEntityBase(id);
        boolean modified =  dod.modifyUserEntityBase(obj);
        Integer currentVersion = obj.getVersion();
        UserEntityBase merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserEntityBase' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to initialize correctly", dod.getRandomUserEntityBase());
        UserEntityBase obj = dod.getNewTransientUserEntityBase(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserEntityBase' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserEntityBase' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserIntegrationTest.testRemove() {
        UserEntityBase obj = dod.getRandomUserEntityBase();
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserEntityBase' failed to provide an identifier", id);
        obj = UserEntityBase.findUserEntityBase(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserEntityBase' with identifier '" + id + "'", UserEntityBase.findUserEntityBase(id));
    }
    
}
