// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.AlgorithmEntity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AlgorithmEntity_Roo_Configurable {
    
    declare @type: AlgorithmEntity: @Configurable;
    
}
