// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.GroupEntity;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect GroupEntity_Roo_Jpa_Entity {
    
    declare @type: GroupEntity: @Entity;
    
    declare @type: GroupEntity: @Table(name = "group_table");
    
}
