// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.JobEntityBase;
import javax.persistence.Entity;

privileged aspect JobEntityBase_Roo_Jpa_Entity {
    
    declare @type: JobEntityBase: @Entity;
    
}
