// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.algorithms.entity;

import io.algorithms.entity.UserEntityBase;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect UserEntityBase_Roo_Jpa_Entity {
    
    declare @type: UserEntityBase: @Entity;
    
    declare @type: UserEntityBase: @Table(name = "user_table");
    
}
